AppBundle\Entity\Task:
    type: entity
    table: task
    indexes:
        fk_task_user1_idx:
            columns:
                - user_id
        fk_task_project1_idx:
            columns:
                - project_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        description:
            type: text
            nullable: true
            length: 255
            options:
                fixed: false
        dueDate:
            type: datetime
            nullable: true
            column: due_date
        attachment:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        workcpaceId:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: workcpace_id
    manyToOne:
        project:
            targetEntity: Project
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                project_id:
                    referencedColumnName: id
            orphanRemoval: false
        user:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
